[package]
name = "tilesheetgen"
version = "0.1.0"
authors = ["Dmitriy Pogretskiy <dpogretskiy@gmail.com>"]
build = "build.rs"

[dependencies]
serde_json = "*"
serde = "*"
serde_derive = "*"
find_folder = "*"
nalgebra = "*"

ggez = { version = "*", features = ["cargo-resource-root"] }
image = "*"

[target.'cfg(windows)'.dependencies]
native-windows-gui = "0.2.0"

[target.'cfg(unix)'.dependencies]
gtk = {version = "0.2.0", features = ["v3_16"] }
